apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
data:
  settings.yml: |
    use_default_settings: true

    server:
      port: 8080
      bind_address: 0.0.0.0
      secret_key: "2bf661a27c10b215f7eb9b2c720c23f168f099db42f1c56911a29e164c556b7d"
      limiter: false
      trusted_proxies:
        - 0.0.0.0/0

    search:
      safe_search: 0
      formats:
        - html
        - json

    ui:
      static_use_hash: true
  limiter.toml: |
    [limiter]
    enabled = true

    [limiter.ip]
    limit = 50
    window = 60