apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
data:
  settings.yml: |
    use_default_settings: true

    server:
      port: 8080
      bind_address: 0.0.0.0
      secret_key: "change-this-secret"
      limiter: false
      trusted_proxies:
        - 0.0.0.0/0

    search:
      safe_search: 0
      formats:
        - html
        - json

    ui:
      static_use_hash: true